### ISSUE TITLE
Reproducible segfault

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparkxgb#2]
```r
library(sparkxgb)
library(sparklyr)
sc <- spark_connect(master = "local")

iris_tbl <- sdf_copy_to(sc, iris)
xgb_model <- xgboost_classifier(
  iris_tbl, Species ~ ., num_class = 3,
  objective = "binary:logistic")
```

**Comment by javierluraschi** [comment]
Few interesting entries...

```
19/01/29 15:48:48 ERROR sparklyr: Gateway (51091) failed calling getThresholds on 95: java.util.NoSuchElementException: Failed to find a default value for thresholds
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getOrDefault(params.scala:779)
	at org.apache.spark.ml.PipelineStage.getOrDefault(Pipeline.scala:42)
	at org.apache.spark.ml.param.Params$class.$(params.scala:786)
	at org.apache.spark.ml.PipelineStage.$(Pipeline.scala:42)
	at org.apache.spark.ml.param.shared.HasThresholds$class.getThresholds(sharedParams.scala:204)
	at org.apache.spark.ml.classification.ProbabilisticClassifier.getThresholds(ProbabilisticClassifier.scala:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
```

```
19/01/29 15:48:52 INFO RabitTracker$TrackerProcessLogger: 2019-01-29 15:48:52,834 INFO @tracker 2.01848483086 secs between node start and job finish
19/01/29 15:48:52 WARN BlockManager: Putting block rdd_43_0 failed due to exception ml.dmlc.xgboost4j.java.XGBoostError: [15:48:50] /Users/nanzhu/code/xgboost/src/objective/regression_obj.cu:66: Check failed: preds.Size() == info.labels_.Size() (450 vs. 150) labels are not correctly providedpreds.size=450, label.size=150

Stack trace returned 7 entries:
[bt] (0) 0   libxgboost4j1483351542626140834.dylib 0x000000012c1297d6 dmlc::StackTrace() + 246
[bt] (1) 1   libxgboost4j1483351542626140834.dylib 0x000000012c12958f dmlc::LogMessageFatal::~LogMessageFatal() + 47
[bt] (2) 2   libxgboost4j1483351542626140834.dylib 0x000000012c1b58fd xgboost::obj::RegLossObj<xgboost::obj::LogisticClassification>::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*) + 589
[bt] (3) 3   libxgboost4j1483351542626140834.dylib 0x000000012c18a144 xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*) + 996
[bt] (4) 4   libxgboost4j1483351542626140834.dylib 0x000000012c132464 XGBoosterUpdateOneIter + 180
[bt] (5) 5   ???                                 0x000000011158e667 0x0 + 4586006119
[bt] (6) 6   ???                                 0x000000011157dd00 0x0 + 4585938176
```

**Comment by kevinykuo** [comment]
Investigation results

1. R session crashes because Spark session didn't exit gracefully.
2. Spark error due to bad user inputs.

We'll eventually fix sparklyr to not crash R, and for now we'll add more checks in sparkxgb functions.
