### ISSUE TITLE
I have a problem using sparkxgb.

### ISSUE THREAD

**Issue by leesiwook95** [rstudio/sparkxgb#43]
Error: java.lang.ClassNotFoundException: ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:111)
...
I already got xgboost4j and xgboost4j-spark in maven.
and i use spark ver = 3.3.0

**Comment by MrCondeMx** [comment]
I have the same issue, cant run xgboost
